In [23]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv('insurance_modified.csv')

In [4]:
df

,age,is_female,bmi,children,is_smoker,charges,region_southeast,bmi_category_Over_weight,bmi_category_Obese
0,-1.440418,1,-0.517949,-0.909234,1,16884,0,1,0
1,-1.511647,0,0.462463,-0.079442,0,1725,1,0,1
2,-0.799350,0,0.462463,1.580143,0,4449,1,0,1
3,-0.443201,0,-1.334960,-0.909234,0,21984,0,0,0
4,-0.514431,0,-0.354547,-0.909234,0,3866,0,1,0
...,...,...,...,...,...,...,...,...,...
1332,0.767704,0,-0.027743,1.580143,0,10600,0,0,1
1333,-1.511647,1,0.135659,-0.909234,0,2205,0,0,1
1334,-1.511647,1,0.952670,-0.909234,0,1629,1,0,1
1335,-1.297958,1,-0.844753,-0.909234,0,2007,0,1,0
1336,1.551231,1,-0.191145,-0.909234,1,29141,0,1,0

In [5]:
df.head()

,age,is_female,bmi,children,is_smoker,charges,region_southeast,bmi_category_Over_weight,bmi_category_Obese
0,-1.440418,1,-0.517949,-0.909234,1,16884,0,1,0
1,-1.511647,0,0.462463,-0.079442,0,1725,1,0,1
2,-0.799350,0,0.462463,1.580143,0,4449,1,0,1
3,-0.443201,0,-1.334960,-0.909234,0,21984,0,0,0
4,-0.514431,0,-0.354547,-0.909234,0,3866,0,1,0


LINEAR-REGRSSION MODEL IN ML

In [16]:
X=df.drop('charges',axis=1)
y=df['charges']

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [18]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [20]:
y_prediction =model.predict(X_test)

In [21]:
y_prediction

array([ 7754.07310392,  5459.65479509, 14595.1862808 , 32476.59588074,
        8935.83935978, 13322.92920106, 30188.2149999 ,  1284.85894847,
       11200.86344909, 10066.40774904, 10721.40470741, 32200.31991713,
       31568.03179991, 16127.51438749, 10250.15479051,  8535.99791746,
        5505.25621343, 32475.52433185,  3199.70899622,  3927.59452679,
        4787.31282873, 28847.01007211, 13805.95385229, 29591.9548251 ,
       31514.48517802,  6360.8525602 , 34985.58864998, 37901.12065686,
       12528.78406392, 14234.68174398,  7604.5440617 , 13034.09395778,
         425.11500206, 11392.67792716, 37469.11807632, 13355.7286057 ,
        3761.39180927,  4469.93538952, 31414.24750396,  8066.36945041,
        6030.33921565, 30326.45440933, 35288.02907735, 13120.4399843 ,
        7905.82391115,  3062.73923367,  5119.65822162,  7654.92786597,
        3599.88939461, 10426.88664139,  7848.13249189, 10429.29757756,
       30407.60973407,  4717.18156056, 11670.49191614, 11503.30387646,
        9406.15858587,  2401.79650917, 31730.57957886, 11009.28361541,
       14797.67549756,  9131.76543119, 13893.45765446,   592.03746551,
       15504.13061137,  9974.34304123, 10305.23943778, 29965.48565819,
       24005.92763433, 16252.35005319,  8238.83441862,  4293.87145549,
        6387.28260019,   913.06477885,  9944.84677218,    44.44213581,
       15974.80444271,  9184.73316526,  8278.77585642, 11186.42136049,
        7065.85587538, 16492.66379455, 15148.43878876, 11667.88234187,
       35001.91527957, 11844.06094939,  3489.23780082,  1125.99916436,
        5546.15678878,  5379.54763693, 16261.22874982, 27883.24667051,
        5390.36799098,  5051.26361692,  1075.64100456, 36328.07358646,
       13572.20325627,  7983.7907738 ,  5213.81139588,  8000.27110839,
       15550.62142685, 15766.62960094, 32186.68628629, 15021.68484796,
       33539.98681955,   222.04689749, 31969.63555017, 26486.00076019,
       14803.55976067,  5433.1199033 ,  9835.230721  , 10677.34411672,
        9051.79632885, 10125.51776291,  5960.20794749,  5875.59858443,
        1365.05513566,  4220.55172524,  6122.75572644,  8978.47379632,
       36726.48887463,  8361.35733531, 11626.78312843, 10135.93448491,
        7986.40034807, 11174.44096864,  4562.84456138, 11504.86754631,
       29371.48854204, 39129.09006107, 34670.44279747, 11659.00364524,
        1996.73872059, 10384.85393487, 10290.67511613,  6525.05077587,
       34493.68530212, 30037.61916605, 24158.6375791 ,  5780.57249937,
        5460.61393265,  3970.72442668, 34655.07530544,  9985.94598563,
        4881.18113814,  9673.6420796 ,  9225.63374061,  7738.08543041,
       35359.69837089, 15314.75391763, 10664.78483705,  6385.74457482,
        8982.2439485 , 16459.56575741,  6507.77202815, 27621.99448561,
       34572.9892899 , 13807.40565091, 11574.97317   , 12334.9749057 ,
       13398.36584451,  4348.37441266, 14060.73192088, 14474.20419177,
       37143.72849543, 34382.65345861, 14026.39449087, 24528.02081255,
        1947.22502484,  2247.54853902,  4274.70287943,  4786.15505308,
        3724.52642222,  9808.11413911, 11576.0447189 , 27347.25428522,
        1944.2636476 , 11740.13052323,  7546.8573997 , 13284.63819998,
       16140.73932185,  6031.4969913 , 10395.27065687,  9893.30238999,
       34079.25389369,  9862.26809557,  7654.81599475,  7241.92261168,
         374.75684226, 32104.60307302,  6940.44132186, 32354.45321378,
       13232.62960346,  4672.53927978,   662.16873367,  3972.8156954 ,
       33471.97246458,  4302.19690878, 12286.18502527, 16954.65756736,
       27637.63035615, 25358.50561939,  5128.64878948, 13408.20367869,
       27272.42497634,  9051.79632885, 11327.15091342, 11671.07080396,
        2068.9006752 , 34294.19051889, 31027.33857162,  9073.72696622,
        4838.27552082,  6951.08232643, 10469.90132765,  4703.57637647,
        5451.70959154, 11423.13613603,  8538.11483065,  4293.87145549,
        2565.53051052, 36611.02456663, 35729.95451514, 13006.24532318,
       12704.35813915, 38726.03451218, 35335.39280363,  7990.51950096,
       27554.47279171,  3738.39718253, 15559.30148538, 31279.77544445,
        7284.5598505 , 10513.61291764,  9410.27773876,  8276.77361672,
       10225.35375991,  4538.41902324,  6362.39058557,  3182.64977381,
        7158.76504725,  6292.83820523,  4108.38775056,  8525.66742221,
         757.77370656,  8361.35453303,  3641.25418428, 11711.01224176,
         909.90476351, 12043.06361167,  5161.91521071, 10263.29295801,
       11186.42136049, 15383.34716042, 37691.20915162, 23056.72855437,
        9810.72371338,  9133.41586791,  7901.70475826, 13409.27522758,
       29827.71046308, 38642.87694775, 15805.11924012, 16221.08867393,
       15712.59031798,  6691.74615447, 39016.90044191,  7492.73188999])

In [22]:
y_test

899      8688
1063     5708
1255    11436
298     38746
237      4463
        ...
534     13831
542     13887
759      3925
1283    47403
1284     8534
Name: charges, Length: 268, dtype: int64

Model Evluation

In [24]:
r2=  r2_score(y_test,y_prediction)
r2

0.8040264119369985

In [26]:
n=X_test.shape[0]
p=X_test.shape[1]
adjusted_R2=( 1-(1-r2)*(n-1)/(n-p-1))

In [27]:
adjusted_R2

0.7979731736956703